// Generated by rgit agent install; changes are overwritten. Remove with: rgit agent uninstall __HARNESS__
//
// Gives each __HARNESS__ session the repository state from `rgit hook session-start`, and with
// `rgit agent install --mcp` registers rgit's MCP tools as native tools that run `rgit tool <name>`.
// All git logic lives in the rgit binary; this file only maps.
import { spawn } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { Type } from "typebox";

// rgit agent install fills in the binary, whether the session hook is on, and the tool definitions.
const RGIT: string = "__RGIT__";
const SESSION_START: string = "__SESSION_START__";
const TOOLS_JSON: string = "__TOOLS__";
const HOOK_TIMEOUT_MS = 10000;
// A tool may fetch or push, so it gets longer than the hook.
const TOOL_TIMEOUT_MS = 120000;

interface ToolDef {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
}
const TOOLS: ToolDef[] = TOOLS_JSON.startsWith("[") ? JSON.parse(TOOLS_JSON) : [];

interface Ran {
  code: number | null;
  out: string;
}

/** Runs rgit in `cwd` with `input` on stdin; undefined when it cannot start or takes longer than `timeoutMs`. */
function runRgit(args: string[], input: string, cwd: string, timeoutMs: number): Promise<Ran | undefined> {
  return new Promise((resolve) => {
    let out = "";
    let done = false;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const finish = (value?: Ran) => {
      if (done) return;
      done = true;
      if (timer) clearTimeout(timer);
      resolve(value);
    };
    let child: ReturnType<typeof spawn>;
    try {
      child = spawn(RGIT, args, { cwd, stdio: ["pipe", "pipe", "ignore"] });
    } catch {
      return finish();
    }
    timer = setTimeout(() => {
      child.kill("SIGKILL");
      finish();
    }, timeoutMs);
    child.on("error", () => finish());
    child.stdout?.on("data", (d: Buffer) => {
      out += d.toString();
    });
    child.on("close", (code: number | null) => finish({ code, out }));
    child.stdin?.on("error", () => {});
    child.stdin?.end(input);
  });
}

function cwdOf(ctx: any): string {
  return String(ctx?.cwd ?? process.cwd());
}

export default function rgit(pi: ExtensionAPI) {
  for (const tool of TOOLS) {
    pi.registerTool({
      name: tool.name,
      label: tool.name,
      description: tool.description,
      promptSnippet: tool.description.split(". ")[0],
      parameters: Type.Unsafe(tool.inputSchema),
      async execute(_id: string, params: unknown, _signal: unknown, _onUpdate: unknown, ctx: any) {
        const r = await runRgit(["tool", tool.name], JSON.stringify(params ?? {}), cwdOf(ctx), TOOL_TIMEOUT_MS);
        if (!r) throw new Error("rgit did not run: check that the rgit command is installed.");
        const text = r.out.trim();
        if (r.code !== 0) throw new Error(text || `rgit exited with ${r.code}`);
        return { content: [{ type: "text", text }], details: {} };
      },
    });
  }

  if (SESSION_START !== "yes") return;
  let startContext: string | undefined;

  pi.on("session_start", async (_event: any, ctx: any) => {
    try {
      const r = await runRgit(["hook", "session-start"], "", cwdOf(ctx), HOOK_TIMEOUT_MS);
      startContext = r && r.code === 0 && r.out.trim() ? r.out.trim() : undefined;
    } catch {
      startContext = undefined;
    }
  });

  // The session-start text goes in once, hidden, with the first prompt.
  pi.on("before_agent_start", async () => {
    const content = startContext;
    startContext = undefined;
    if (!content) return undefined;
    return { message: { customType: "rgit", content, display: false } };
  });
}
